package com.andrew.hdss.ui.viewmodels

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.andrew.hdss.data.daos.AnswerDao
import com.andrew.hdss.data.daos.ChoiceDao
import com.andrew.hdss.data.daos.FormDao
import com.andrew.hdss.data.daos.FormResponseDao
import com.andrew.hdss.data.daos.HouseholdDao
import com.andrew.hdss.data.daos.IndividualDao
import com.andrew.hdss.data.daos.MembershipDao
import com.andrew.hdss.data.daos.QuestionDao
import com.andrew.hdss.data.models.Answer
import com.andrew.hdss.data.models.Choice
import com.andrew.hdss.data.models.Form
import com.andrew.hdss.data.models.FormResponse
import com.andrew.hdss.data.models.Question
import com.andrew.hdss.data.models.enums.FormResponseStatus
import com.andrew.hdss.data.models.enums.MappedEntity
import com.andrew.hdss.data.models.enums.QuestionType
import com.andrew.hdss.util.AnswerEntityMapper
import com.andrew.hdss.util.ExpressionEvaluator
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import java.time.LocalDateTime
import java.util.UUID
import kotlin.collections.associate
import kotlin.collections.filter

// entityClientIds: the clientId to use when THIS form's own answers
// build an entity (pre-generated by the caller so a Visit or a sibling
// form created earlier can already reference it correctly).
// foreignKeys: values this form needs but never asks about directly
// (e.g. "householdClientId" when filling head-of-household-registration).
data class FormFillContext(
    val locationId: Long? = null, // supplied externally; see note above on removing location_id as a Question
    val entityClientIds: Map<MappedEntity, String> = emptyMap(),
    val foreignKeys: Map<String, String> = emptyMap()
)

data class FormFillUiState(
    val form: Form? = null,
    val allQuestions: List<Question> = emptyList(),
    val choicesByListName: Map<String, List<Choice>> = emptyMap(),
    val answers: Map<Long, String> = emptyMap(),
    val visibleQuestions: List<Question> = emptyList(),
    val currentIndex: Int = 0,
    val constraintError: String? = null,
    val isSaving: Boolean = false,
    val isComplete: Boolean = false
)

class FormFillViewModel(
    private val formId: Long,
    private val visitId: String,
    private val context: FormFillContext,
    private val formDao: FormDao,
    private val questionDao: QuestionDao,
    private val choiceDao: ChoiceDao,
    private val formResponseDao: FormResponseDao,
    private val answerDao: AnswerDao,
    private val householdDao: HouseholdDao,
    private val individualDao: IndividualDao,
    private val membershipDao: MembershipDao
) : ViewModel() {

    private val evaluator = ExpressionEvaluator()
    private val _uiState = MutableStateFlow(FormFillUiState())
    val uiState: StateFlow<FormFillUiState> = _uiState.asStateFlow()

    private val startedAt: LocalDateTime = LocalDateTime.now()

    init {
        viewModelScope.launch { loadForm() }
    }

    private suspend fun loadForm() {
        val form = formDao.getById(formId)

        val questions = questionDao.getByFormId(formId)
        val listNames = questions.mapNotNull { it.choiceListName }.distinct()
        val choicesByListName = listNames.associateWith { name ->
            choiceDao.getAllByListName(name).sortedBy { it.orderIndex }
        }

        _uiState.update {
            it.copy(
                form = form,
                allQuestions = questions,
                choicesByListName = choicesByListName,
                visibleQuestions = recomputeVisible(questions, emptyMap())
            )
        }
    }

    private fun answersAsStrings(answers: Map<Long, String>, questions: List<Question>): Map<String, String?> =
        questions.associate { q -> q.name to answers[q.id] }

    private fun recomputeVisible(questions: List<Question>, answers: Map<Long, String>): List<Question> {
        val answerContext = answersAsStrings(answers, questions)
        return questions.filter { q ->
            q.relevant.isNullOrBlank() || evaluator.evaluate(q.relevant, answerContext).asBoolean()
        }
    }

    private fun recomputeCalculations(questions: List<Question>, answers: Map<Long, String>): Map<Long, String> {
        val updated = answers.toMutableMap()
        val answerContext = answersAsStrings(updated, questions)
        questions.filter { it.type == QuestionType.CALCULATE }.forEach { q ->
            val calc = q.calculation
            if (!calc.isNullOrBlank()) {
                updated[q.id] = evaluator.evaluate(calc, answerContext).asString()
            }
        }
        return updated
    }

    fun updateAnswer(question: Question, rawValue: String) {
        val state = _uiState.value
        var updatedAnswers = state.answers + (question.id to rawValue)
        updatedAnswers = recomputeCalculations(state.allQuestions, updatedAnswers)
        val visible = recomputeVisible(state.allQuestions, updatedAnswers)
        _uiState.update {
            it.copy(answers = updatedAnswers, visibleQuestions = visible, constraintError = null)
        }
    }

    fun goNext() {
        val state = _uiState.value
        val current = state.visibleQuestions.getOrNull(state.currentIndex) ?: return

        if (current.required && state.answers[current.id].isNullOrBlank() &&
            current.type != QuestionType.NOTE && current.type != QuestionType.CALCULATE) {
            _uiState.update { it.copy(constraintError = "This question is required.") }
            return
        }

        val constraint = current.constraint
        val value = state.answers[current.id]
        if (!constraint.isNullOrBlank() && !value.isNullOrBlank()) {
            val answerContext = answersAsStrings(state.answers, state.allQuestions)
            val satisfied = evaluator.evaluate(constraint, answerContext, selfValue = value).asBoolean()
            if (!satisfied) {
                _uiState.update { it.copy(constraintError = current.constraintMessage ?: "Invalid value.") }
                return
            }
        }

        val nextIndex = state.currentIndex + 1
        if (nextIndex >= state.visibleQuestions.size) {
            submit()
        } else {
            _uiState.update { it.copy(currentIndex = nextIndex, constraintError = null) }
        }
    }

    fun goBack() {
        _uiState.update { it.copy(currentIndex = (it.currentIndex - 1).coerceAtLeast(0), constraintError = null) }
    }

    private fun submit() {
        val state = _uiState.value
        val form = state.form ?: return

        viewModelScope.launch {
            _uiState.update { it.copy(isSaving = true) }
            try {
                val formResponseId = UUID.randomUUID().toString()
                formResponseDao.insert(
                    FormResponse(
                        id = formResponseId,
                        visitId = visitId,
                        formId = form.id,
                        formVersion = form.version,
                        status = FormResponseStatus.COMPLETED,
                        startedAt = startedAt,
                        completedAt = LocalDateTime.now(),
                        synced = false
                    )
                )

                val answerRows = state.visibleQuestions
                    .filter { state.answers.containsKey(it.id) }
                    .map { q ->
                        Answer(
                            id = UUID.randomUUID().toString(),
                            formResponseId = formResponseId,
                            questionId = q.id,
                            value = state.answers.getValue(q.id),
                            synced = false
                        )
                    }
                answerDao.insertAll(answerRows)

                val bags = AnswerEntityMapper.buildFieldBags(state.visibleQuestions, state.answers)

                bags[MappedEntity.HOUSEHOLD]?.let { fields ->
                    val clientId = context.entityClientIds.getValue(MappedEntity.HOUSEHOLD)
                    val locationId = context.locationId
                        ?: throw IllegalStateException("locationId is required to build a Household")
                    householdDao.insert(AnswerEntityMapper.buildHousehold(clientId, locationId, fields))
                }

                bags[MappedEntity.INDIVIDUAL]?.let { fields ->
                    val clientId = context.entityClientIds.getValue(MappedEntity.INDIVIDUAL)
                    individualDao.insert(AnswerEntityMapper.buildIndividual(clientId, fields))
                }

                bags[MappedEntity.MEMBERSHIP]?.let { fields ->
                    val clientId = context.entityClientIds.getValue(MappedEntity.MEMBERSHIP)
                    val individualClientId = context.entityClientIds[MappedEntity.INDIVIDUAL]
                        ?: context.foreignKeys.getValue("individualClientId")
                    val householdClientId = context.foreignKeys.getValue("householdClientId")
                    val membership = AnswerEntityMapper.buildMembership(clientId, individualClientId, householdClientId, fields)
                    membershipDao.insert(membership)
                    AnswerEntityMapper.applyHeadOfHouseholdRulesLocally(membership, householdDao)
                }

                _uiState.update { it.copy(isSaving = false, isComplete = true) }
            } catch (e: Exception) {
                _uiState.update { it.copy(isSaving = false, constraintError = "Failed to save: ${e.message}") }
            }
        }
    }
}